server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # use 'validate' or 'none' in production
    show-sql: true         # show SQL queries in logs
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      indent_output: true

# Optional: For logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
